{{- if and (eq .Values.global.platform "openshift") .Values.podLogs.lokiReceiver.enabled .Values.podLogs.openShiftClusterLogForwarder.enabled }}
{{- /* https://docs.openshift.com/container-platform/4.17/observability/logging/logging-6.1/log6x-clf-6.1.html */}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.fullname" . }}-clf
  namespace: openshift-logging
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helper.fullname" . }}-clf-application-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-application-logs
subjects:
  - kind: ServiceAccount
    name: {{ include "helper.fullname" . }}-clf
    namespace: openshift-logging
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helper.fullname" . }}-clf-infrastructure-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-infrastructure-logs
subjects:
  - kind: ServiceAccount
    name: {{ include "helper.fullname" . }}-clf
    namespace: openshift-logging
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: {{ include "helper.fullname" . }}
  namespace: openshift-logging
spec:
  serviceAccountName: {{ include "helper.fullname" . }}-clf
  inputs:
{{- if .Values.podLogs.openShiftClusterLogForwarder.application.enabled }}
    - name: apps
      application:
        namespaces: {{ .Values.podLogs.openShiftClusterLogForwarder.application.namespaces | toJson }}
{{- end }}
{{- if .Values.podLogs.openShiftClusterLogForwarder.infrastructure.enabled }}
    - name: infra
      infrastructure:
        sources:
          - node
{{- end }}
  outputs:
    - name: {{ include "helper.fullname" . }}
      type: loki
      url: {{ include "features.podLogs.receiver.loki" . | trim }}
  pipelines:
    - name: {{ include "helper.fullname" . }}
      inputRefs:
{{- if .Values.podLogs.openShiftClusterLogForwarder.application.enabled }}
        - apps
{{- end }}
{{- if .Values.podLogs.openShiftClusterLogForwarder.infrastructure.enabled }}
        - infra
{{- end }}
      outputRefs:
        - {{ include "helper.fullname" . }}
{{- end }}

TODO:
- loki receiver should go into alloy receivers
- CLF For infra should go into node logs
- PodLogs just handles CLF for application logs
- Need proper processing stages for log data
