---
# Source: k8s-monitoring/templates/remote_config_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "alloy-metrics-remote-cfg-k8smon-k8s-monitoring"
  namespace: "default"
type: Opaque
data:
  username: "bXktcmVtb3RlLWNmZy11c2Vy"
# create: true
---
# Source: k8s-monitoring/templates/remote_config_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "alloy-logs-remote-cfg-k8smon-k8s-monitoring"
  namespace: "default"
type: Opaque
data:
  username: "bXktcmVtb3RlLWNmZy11c2Vy"
---
# Source: k8s-monitoring/templates/alloy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8smon-alloy-metrics
  namespace: default
data:
  config.alloy: |-
    
    
    
    remote.kubernetes.secret "alloy_metrics_remote_cfg" {
      name      = "alloy-metrics-remote-cfg-k8smon-k8s-monitoring"
      namespace = "default"
    }
    
    remotecfg {
      id = sys.env("GCLOUD_FM_COLLECTOR_ID")
      url = "https://remote-config.example.com/alloy"
      basic_auth {
        username = nonsensitive(remote.kubernetes.secret.alloy_metrics_remote_cfg.data["username"])
        password = sys.env("GCLOUD_RW_API_KEY")
      }
      poll_frequency = 
      attributes = {
        "platform" = "kubernetes",
        "source" = "k8s-monitoring",
        "sourceVersion" = "2.0.6",
        "release" = "k8smon",
        "cluster" = "remote-config-example-cluster",
        "namespace" = "default",
        "workloadType" = "statefulset",
      }
    }
---
# Source: k8s-monitoring/templates/alloy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8smon-alloy-logs
  namespace: default
data:
  config.alloy: |-
    
    
    
    remote.kubernetes.secret "alloy_logs_remote_cfg" {
      name      = "alloy-logs-remote-cfg-k8smon-k8s-monitoring"
      namespace = "default"
    }
    
    remotecfg {
      id = sys.env("GCLOUD_FM_COLLECTOR_ID")
      url = "https://remote-config.example.com/alloy"
      basic_auth {
        username = nonsensitive(remote.kubernetes.secret.alloy_logs_remote_cfg.data["username"])
        password = sys.env("GCLOUD_RW_API_KEY")
      }
      poll_frequency = 
      attributes = {
        "platform" = "kubernetes",
        "source" = "k8s-monitoring",
        "sourceVersion" = "2.0.6",
        "release" = "k8smon",
        "cluster" = "remote-config-example-cluster",
        "namespace" = "default",
        "workloadType" = "daemonset",
      }
    }
---
# Source: k8s-monitoring/templates/remote_config_secret.yaml
# create: true
---
# Source: k8s-monitoring/templates/alloy.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8smon-alloy-metrics
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: k8smon
        namespace: default
      interval: 1m
  values: 
    alloy:
      clustering:
        enabled: true
        name: alloy-metrics
      configMap:
        create: false
      extraEnv:
      - name: CLUSTER_NAME
        value: remote-config-example-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: $(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
      - name: GCLOUD_RW_API_KEY
        value: my-remote-cfg-password
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations:
        k8s.grafana.com/logs.job: integrations/alloy
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETGID
          - SETUID
          - SETPCAP
          - NET_BIND_SERVICE
          - NET_RAW
          - SYS_CHROOT
          - MKNOD
          - AUDIT_WRITE
          - SETFCAP
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      stabilityLevel: public-preview
    collectorName: alloy-metrics
    controller:
      replicas: 1
      type: statefulset
    crds:
      create: false
    enabled: true
    extraConfig: ""
    liveDebugging:
      enabled: false
    logging:
      format: logfmt
      level: info
    remoteConfig:
      auth:
        password: ""
        passwordFrom: sys.env("GCLOUD_RW_API_KEY")
        passwordKey: password
        type: basic
        username: my-remote-cfg-user
        usernameFrom: ""
        usernameKey: username
      enabled: true
      extraAttributes: {}
      name: alloy-metrics-remote-cfg
      pollFrequency: 5m
      secret:
        create: true
        embed: false
        name: ""
        namespace: ""
      type: remoteConfig
      url: https://remote-config.example.com/alloy
---
# Source: k8s-monitoring/templates/alloy.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8smon-alloy-logs
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: k8smon
        namespace: default
      interval: 1m
  values: 
    alloy:
      configMap:
        create: false
      extraEnv:
      - name: CLUSTER_NAME
        value: remote-config-example-cluster
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: $(CLUSTER_NAME)-$(NAMESPACE)-$(NODE_NAME)
      - name: GCLOUD_RW_API_KEY
        value: my-remote-cfg-password
      mounts:
        dockercontainers: true
        varlog: true
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations:
        k8s.grafana.com/logs.job: integrations/alloy
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETGID
          - SETUID
          - SETPCAP
          - NET_BIND_SERVICE
          - NET_RAW
          - SYS_CHROOT
          - MKNOD
          - AUDIT_WRITE
          - SETFCAP
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
      stabilityLevel: public-preview
    collectorName: alloy-logs
    controller:
      type: daemonset
    crds:
      create: false
    enabled: true
    extraConfig: ""
    liveDebugging:
      enabled: false
    logging:
      format: logfmt
      level: info
    remoteConfig:
      auth:
        password: ""
        passwordFrom: sys.env("GCLOUD_RW_API_KEY")
        passwordKey: password
        type: basic
        username: my-remote-cfg-user
        usernameFrom: ""
        usernameKey: username
      enabled: true
      extraAttributes: {}
      name: alloy-logs-remote-cfg
      pollFrequency: 5m
      secret:
        create: true
        embed: false
        name: ""
        namespace: ""
      type: remoteConfig
      url: https://remote-config.example.com/alloy
---
# Source: k8s-monitoring/templates/temp_helm_repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8smon
  namespace: default
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
